### ISSUE TITLE
You are being rate limited

### ISSUE THREAD

**Issue by amenbros** [theADAMJR/1PG-Demo#2]
```js
UnhandledPromiseRejectionWarning: Error: You are being rate limited 
at C:\1pg\node_modules\disco-oauth\lib\client.js:205:21
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. 
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag '--unhandled-rejections=strict' (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

First time using the dashboard, never spammed the API or anything. Redirects me to a 401 page.

**Comment by theADAMJR** [comment]
Manage Sessions - https://www.youtube.com/watch?v=jkwBzZqeJw4

**Comment by amenbros** [comment]
I'm using the latest source code, the session.js is the same as shown in the video.

**Comment by theADAMJR** [comment]
It happens when auth client is called too many times at a time - updating user/guild multiple times whilst connecting to the route.

**Comment by theADAMJR** [comment]
https://www.diffchecker.com is useful for finding differences with source code.
https://github.com/theADAMJR/1PG code is currently working, and is ahead of the YouTube dashboard series.
